name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          - os: macos-latest
            goos: linux
          - os: macos-latest
            goos: windows
          - os: windows-latest
            goos: linux
          - os: windows-latest
            goos: darwin
          - os: ubuntu-latest
            goos: darwin
          - os: ubuntu-latest
            goos: windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Build binary
        run: |
          mkdir -p dist
          go build -o dist/concat-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/concat

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: concat-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/concat-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
